# Multiple Jobs example
name: workflow_4
on:
  push:
    branches: [ main ]
jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4
      with:
        repository: Joanne0624/Cloned_rs_policy_service
        token: ${{ secrets.GITHUB_TOKEN }}
  display_name_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Welcome to GitHub Actions........'
